### ISSUE TITLE
Are weights and momentum off-chip?

### ISSUE THREAD

**Issue by TTTTTTris** [chuliang007/resnet18_training#2]
Hi, thanks a lot for attaching code to this work! I have a question that that in the ICCAD paper, you claim the weights and momentum are off-chip, while in the code **they are global variables but not interfaces** on top function. Could you explain how do you set the w and m off-chip in the code?

Thanks again.

**Comment by chuliang007** [comment]
We put weights and velocities on-chip for the simplicity of this reference design, and you can refer to FracBNN repo [https://github.com/cornell-zhang/FracBNN/blob/main/xcel-imagenet/source/layer.h] for off-chip weight communication.

**Comment by TTTTTTris** [comment]
Thank you for the information!
